apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
     application: example-php-docker-helloworld 
  name: example-php-docker-helloworld-route 
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: example-php-docker-helloworld
    weight: 100
  tls:
    termination: edge
  wildcardPolicy: None

